tetracup_openscad.stl: tetracup.scad
	/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD -o tetracup_openscad.stl tetracup.scad

open:
	/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD tetracup.scad

clean:
	rm -f tetracup_openscad.stl 
