FOLDER=$(shell pwd)

all: tracelet_from_tetraminos

tracelet_from_tetraminos:
	(cd ~/AbFab3D/apps/volumesculptor/; ant runShell "-Dscript=$(FOLDER)/tracelet_from_tetraminos.js" "-DoutputFolder=$(FOLDER)")

